# Generated by Django 4.0.3 on 2023-04-22 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0004_alter_work_category'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='work',
            table='Works',
        ),
    ]
