# Generated by Django 4.0.3 on 2023-06-20 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='designation',
            field=models.CharField(choices=[('wcontrol', 'Wildife Control Officer'), ('wmanager', 'Wildife Control Manager'), ('admin', 'admin')], default='wcontrol', max_length=20),
        ),
    ]
