# Generated by Django 4.0.3 on 2023-04-26 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_alter_profile_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='designation',
            field=models.CharField(choices=[('wcontrol', 'Wildife Control Officer'), ('wmanager', 'Wildife Control Manager')], default='wcontrol', max_length=20),
        ),
    ]
