# Generated by Django 4.0.3 on 2023-01-14 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_first_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='designation',
            field=models.CharField(choices=[('wcontrol', 'Wildife Control Officer'), ('wmanager', 'Wildife Control Manager')], default='wcontrol', max_length=20),
        ),
    ]
