# Generated by Django 4.0.3 on 2023-06-23 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airports', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='airport',
            name='stationid',
            field=models.IntegerField(db_column='stationid', primary_key=True, serialize=False),
        ),
    ]
