version: "3.9"
services:
  backend:
    build:
      context: .
      dockerfile: ./docker/local/django/Dockerfile
    command: /start
    volumes:
      - .:/app
      - static:/app/static
      - media:/app/media
    expose:
      - "8000"
    env_file:
      - .env
    depends_on:
      - yaspidb
    networks:
      - yaspinetwork
    container_name: yaspi_backend
  yaspidb:
    image: kartoza/postgis:latest
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    restart: on-failure
    networks:
      - yaspinetwork
    container_name: yaspi_db
  frontend:
    build:
      context: ./frontend
      dockerfile: ./Dockerfile
    restart: on-failure
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend
    networks:
      - yaspinetwork
    container_name: yaspi_frontend
  nginx:
    restart: always
    depends_on:
      - backend
      - frontend
    volumes:
      - static:/app/static
      - media:/app/media
    build:
      context: ./docker/local/nginx
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    networks:
      - yaspinetwork
    container_name: yaspi_nginx_proxy
networks:
  yaspinetwork:
    driver: bridge
volumes:
  postgres_data:
  static:
  media:
