# Generated by Django 4.0.3 on 2022-10-28 11:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogs',
            options={'ordering': ['-created_date'], 'verbose_name': 'Blogs', 'verbose_name_plural': 'Blogs'},
        ),
        migrations.RenameField(
            model_name='blogs',
            old_name='date',
            new_name='modified_date',
        ),
        migrations.AddField(
            model_name='blogs',
            name='created_date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
