# Generated by Django 4.0.3 on 2023-04-23 18:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('incidentcontrol', '0004_alter_incidentcontrol_damage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incidentcontrol',
            name='flightphase',
            field=models.CharField(choices=[('Landing Roll', 'Landing Roll'), ('Take Off Run', 'Take Off Run'), ('Approach', 'Approach'), ('Climbing', 'Climbing')], default='Take Off Run', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='incidentcontrol',
            name='impact',
            field=models.CharField(choices=[('None', 'Zero'), ('Precautionary', 'Precautionary'), ('Landing', 'Landing'), ('Flight Cancelled', 'Flight Cancelled'), ('Engine Shut Down', 'Engine Shut Down')], default='None', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='incidentcontrol',
            name='pilotwarning',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='incidentcontrol',
            name='verifiedby',
            field=models.ForeignKey(default='staff', null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='incidentverify', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='incidentcontrol',
            name='wildlifenumber',
            field=models.CharField(choices=[('1 to 5', 'Less Than 5'), ('5 to 50', 'Five To 50'), ('More than 50', 'More Than 50')], default='1 to 5', max_length=100, null=True),
        ),
    ]
