# Generated by Django 4.0.3 on 2023-04-25 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidentcontrol', '0006_alter_incidentcontrol_incidentid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incidentcontrol',
            name='airlineoperator',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='incidentcontrol',
            name='scientificname',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
