# Generated by Django 4.0.3 on 2023-01-14 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_designation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='designation',
            field=models.CharField(choices=[('wcontrol', 'Wildife Control Officer'), ('wmanager', 'Wildife Control Manager')], max_length=20),
        ),
    ]
