# Generated by Django 4.0.3 on 2023-04-26 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_user_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='designation',
        ),
    ]
