# Generated by Django 4.0.3 on 2023-06-23 09:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('incident', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IncidentControl',
            fields=[
                ('incidentid', models.OneToOneField(db_column='incidentID', default='staff', on_delete=django.db.models.deletion.SET_DEFAULT, primary_key=True, related_name='incidentidl2', serialize=False, to='incident.incident')),
                ('date', models.DateTimeField(db_column='date', null=True)),
                ('altitude', models.IntegerField(blank=True, db_column='altitude', null=True)),
                ('damage', models.BooleanField(db_column='damageToAircraft', default=False, null=True, verbose_name='Damage to Aircraft')),
                ('impact', models.CharField(choices=[('None', 'Zero'), ('Precautionary', 'Precautionary'), ('Landing', 'Landing'), ('Flight Cancelled', 'Flight Cancelled'), ('Engine Shut Down', 'Engine Shut Down')], db_column='impact', default='None', max_length=100, null=True)),
                ('pilotwarning', models.BooleanField(db_column='pilotWarning', default=False, null=True)),
                ('flightphase', models.CharField(choices=[('Landing Roll', 'Landing Roll'), ('Take Off Run', 'Take Off Run'), ('Approach', 'Approach'), ('Climbing', 'Climbing')], db_column='flightPhase', default='Take Off Run', max_length=100, null=True)),
                ('aircraftmodel', models.CharField(db_column='aircraftModel', max_length=100, null=True)),
                ('scientificname', models.CharField(db_column='scientificName', max_length=100, null=True)),
                ('wildlifenumber', models.CharField(choices=[('1 to 5', 'Less Than 5'), ('5 to 50', 'Five To 50'), ('More than 50', 'More Than 50')], db_column='wildlifeNumber', default='1 to 5', max_length=100, null=True)),
                ('wildlifenumberactual', models.IntegerField(db_column='wildlifeNumberActual', null=True)),
                ('airlineoperator', models.CharField(db_column='airlineOperator', max_length=100, null=True)),
                ('recordedby', models.ForeignKey(db_column='recordedBy', default='staff', on_delete=django.db.models.deletion.SET_DEFAULT, related_name='recorder', to=settings.AUTH_USER_MODEL)),
                ('verifiedby', models.ForeignKey(db_column='verifiedBy', default='staff', null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='incidentverify', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Incident Verification',
                'verbose_name_plural': 'Incident Verification',
                'db_table': 'incidentcontrol',
                'ordering': ['-date'],
            },
        ),
    ]
