# Generated by Django 4.0.3 on 2023-04-23 17:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('incident', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IncidentControl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('altitude', models.IntegerField(blank=True)),
                ('damage', models.BooleanField(default=False, verbose_name='Damage to Aircraft')),
                ('impact', models.CharField(choices=[('None', 'Zero'), ('Precautionary', 'Precautionary'), ('Landing', 'Landing'), ('Flight Cancelled', 'Flight Cancelled'), ('Engine Shut Down', 'Engine Shut Down')], default='None', max_length=100)),
                ('pilotwarning', models.BooleanField(default=False)),
                ('flightphase', models.CharField(choices=[('Landing Roll', 'Landing Roll'), ('Take Off Run', 'Take Off Run'), ('Approach', 'Approach'), ('Climbing', 'Climbing')], default='Take Off Run', max_length=100)),
                ('aircraftmodel', models.CharField(max_length=100)),
                ('scientificname', models.TextField()),
                ('wildlifenumber', models.CharField(choices=[('1 to 5', 'Less Than 5'), ('5 to 50', 'Five To 50'), ('More than 50', 'More Than 50')], default='1 to 5', max_length=100)),
                ('wildlifenumberactual', models.IntegerField()),
                ('airlineoperator', models.TextField()),
                ('incidentid', models.OneToOneField(default='staff', on_delete=django.db.models.deletion.SET_DEFAULT, related_name='incidentidl2', to='incident.incident')),
                ('recordedby', models.ForeignKey(default='staff', on_delete=django.db.models.deletion.SET_DEFAULT, related_name='recorder', to='incident.incident')),
                ('verifiedby', models.ForeignKey(default='staff', on_delete=django.db.models.deletion.SET_DEFAULT, related_name='incidentverify', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Incident Verification',
                'verbose_name_plural': 'Incident Verification',
                'db_table': 'incidentcontrol',
                'ordering': ['-date'],
            },
        ),
    ]
