# Generated by Django 4.0.3 on 2023-06-23 10:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('incident', '0002_alter_incident_incidentid'),
        ('incidentcontrol', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incidentcontrol',
            name='incidentid',
            field=models.OneToOneField(db_column='incidentid', default='staff', on_delete=django.db.models.deletion.SET_DEFAULT, primary_key=True, related_name='incidentidl2', serialize=False, to='incident.incident'),
        ),
    ]
