# Generated by Django 4.0.3 on 2023-04-23 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidentcontrol', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incidentcontrol',
            name='date',
            field=models.DateTimeField(null=True),
        ),
    ]
