# Generated by Django 4.0.3 on 2023-06-21 08:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('incidentcontrol', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incidentcontrol',
            name='recordedby',
            field=models.ForeignKey(db_column='recordedby', default='staff', on_delete=django.db.models.deletion.SET_DEFAULT, related_name='recorder', to=settings.AUTH_USER_MODEL),
        ),
    ]
