# Generated by Django 4.0.3 on 2023-06-23 10:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('incidentcontrol', '0002_alter_incidentcontrol_incidentid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incidentcontrol',
            name='aircraftmodel',
            field=models.CharField(db_column='aircraftmodel', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='incidentcontrol',
            name='airlineoperator',
            field=models.CharField(db_column='airlineoperator', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='incidentcontrol',
            name='damage',
            field=models.BooleanField(db_column='damagetoaircraft', default=False, null=True, verbose_name='Damage to Aircraft'),
        ),
        migrations.AlterField(
            model_name='incidentcontrol',
            name='flightphase',
            field=models.CharField(choices=[('Landing Roll', 'Landing Roll'), ('Take Off Run', 'Take Off Run'), ('Approach', 'Approach'), ('Climbing', 'Climbing')], db_column='flightphase', default='Take Off Run', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='incidentcontrol',
            name='pilotwarning',
            field=models.BooleanField(db_column='pilotwarning', default=False, null=True),
        ),
        migrations.AlterField(
            model_name='incidentcontrol',
            name='recordedby',
            field=models.ForeignKey(db_column='recordedby', default=1, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='recorder', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='incidentcontrol',
            name='scientificname',
            field=models.CharField(db_column='scientificname', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='incidentcontrol',
            name='verifiedby',
            field=models.ForeignKey(db_column='verifiedby', default=1, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='incidentverify', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='incidentcontrol',
            name='wildlifenumber',
            field=models.CharField(choices=[('1 to 5', 'Less Than 5'), ('5 to 50', 'Five To 50'), ('More than 50', 'More Than 50')], db_column='wildlifenumber', default='1 to 5', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='incidentcontrol',
            name='wildlifenumberactual',
            field=models.IntegerField(db_column='wildlifenumberactual', null=True),
        ),
    ]
