# Generated by Django 4.0.3 on 2023-04-23 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidentcontrol', '0002_alter_incidentcontrol_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incidentcontrol',
            name='aircraftmodel',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='incidentcontrol',
            name='airlineoperator',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='incidentcontrol',
            name='altitude',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='incidentcontrol',
            name='scientificname',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='incidentcontrol',
            name='wildlifenumberactual',
            field=models.IntegerField(null=True),
        ),
    ]
