# Generated by Django 4.0.3 on 2023-04-23 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidentcontrol', '0003_alter_incidentcontrol_aircraftmodel_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incidentcontrol',
            name='damage',
            field=models.BooleanField(default=False, null=True, verbose_name='Damage to Aircraft'),
        ),
    ]
