# Generated by Django 4.0.3 on 2023-07-31 17:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('incidentcontrol', '0004_incidentcontrol_is_verified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incidentcontrol',
            name='flightphase',
            field=models.CharField(choices=[('landing roll', 'Landing Roll'), ('take-off run', 'Take-off Run'), ('approach', 'Approach'), ('climbing', 'Climbing')], db_column='flightphase', default='take-off run', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='incidentcontrol',
            name='impact',
            field=models.CharField(choices=[('none', 'None'), ('precautionary', 'Precautionary'), ('landing', 'Landing'), ('flight cancelled', 'Flight Cancelled'), ('engine shutdown', 'Engine Shut Down')], db_column='impact', default='none', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='incidentcontrol',
            name='verifiedby',
            field=models.ForeignKey(blank=True, db_column='verifiedby', default=1, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='incidentverify', to=settings.AUTH_USER_MODEL),
        ),
    ]
