# Generated by Django 4.0.3 on 2023-04-24 04:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('incident', '0002_alter_incident_incidentid_alter_incident_recordedby'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('incidentcontrol', '0005_alter_incidentcontrol_flightphase_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incidentcontrol',
            name='incidentid',
            field=models.OneToOneField(db_column='incidentid', default='staff', on_delete=django.db.models.deletion.SET_DEFAULT, related_name='incidentidl2', to='incident.incident'),
        ),
        migrations.AlterField(
            model_name='incidentcontrol',
            name='recordedby',
            field=models.ForeignKey(db_column='recordedby', default='staff', on_delete=django.db.models.deletion.SET_DEFAULT, related_name='recorder', to='incident.incident'),
        ),
        migrations.AlterField(
            model_name='incidentcontrol',
            name='verifiedby',
            field=models.ForeignKey(db_column='verifiedby', default='staff', null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='incidentverify', to=settings.AUTH_USER_MODEL),
        ),
    ]
