# Generated by Django 4.0.3 on 2023-08-02 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidentcontrol', '0005_alter_incidentcontrol_flightphase_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incidentcontrol',
            name='damage',
            field=models.BooleanField(db_column='damage', default=False, null=True, verbose_name='Damage to Aircraft'),
        ),
    ]
