# Generated by Django 4.0.3 on 2023-08-02 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidentcontrol', '0006_alter_incidentcontrol_damage'),
    ]

    operations = [
        migrations.AddField(
            model_name='incidentcontrol',
            name='date_modified',
            field=models.DateTimeField(auto_now=True, db_column='date_modified', null=True),
        ),
        migrations.AlterField(
            model_name='incidentcontrol',
            name='date',
            field=models.DateTimeField(auto_now_add=True, db_column='date_verified', null=True),
        ),
    ]
