# Generated by Django 4.0.3 on 2022-10-05 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('category', models.CharField(choices=[('agriculture', 'agriculture'), ('biodiversity', 'biodiversity'), ('water', 'water'), ('facility', 'facility')], default='agriculture', max_length=20)),
                ('software', models.TextField()),
                ('release_date', models.DateField()),
                ('is_published', models.BooleanField(default=False, help_text='Publish Status', verbose_name='Publish Status')),
            ],
            options={
                'verbose_name': 'Works',
                'verbose_name_plural': 'Works',
                'ordering': ['title'],
            },
        ),
    ]
