# Generated by Django 4.0.3 on 2023-01-13 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0002_work_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work',
            name='category',
            field=models.CharField(choices=[('agriculture', 'AGRICULTURE'), ('biodiversity', 'BIODIVERSITY'), ('water', 'WATER'), ('facility', 'FACILITY')], default='agriculture', max_length=20),
        ),
    ]
