# Generated by Django 4.0.3 on 2023-01-14 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0003_alter_work_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work',
            name='category',
            field=models.CharField(choices=[('agriculture', 'Agriculture'), ('biodiversity', 'Biodiversity'), ('water', 'Water'), ('facility', 'Facility')], default='agriculture', max_length=20),
        ),
    ]
