# Generated by Django 4.0.3 on 2023-04-22 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0005_alter_work_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='work',
            table='works',
        ),
    ]
