# Generated by Django 4.0.3 on 2023-04-22 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('banner', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='banner',
            table='banner',
        ),
    ]
