# Generated by Django 4.0.3 on 2023-06-23 09:54

from django.conf import settings
import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('airports', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('incidentid', models.UUIDField(db_column='incidentID', default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('incidentdate', models.DateTimeField(auto_now_add=True, db_column='incidentDate')),
                ('precipitation', models.CharField(choices=[('Light Rain', 'Lightrain'), ('Heavy Fog', 'Heavyfog'), ('Fog', 'Fog'), ('None', 'Zero')], db_column='precipiation', default='None', max_length=50)),
                ('location', django.contrib.gis.db.models.fields.PointField(db_column='location', srid=4326)),
                ('locationremarks', models.TextField(blank=True, db_column='locationRemarks')),
                ('speciestype', models.CharField(choices=[('Mammal', 'Mammal'), ('Bird', 'Bird'), ('Other', 'Other')], db_column='speciesType', default='Bird', max_length=50)),
                ('speciesname', models.CharField(blank=True, db_column='speciesName', max_length=100)),
                ('incidentremarks', models.TextField(blank=True, db_column='incidentRemarks')),
                ('image', models.ImageField(blank=True, db_column='image', default='default.png', null=True, upload_to='')),
                ('airport', models.ForeignKey(db_column='airport', default=1, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='incidentairport', to='airports.airport')),
                ('recordedby', models.ForeignKey(db_column='recordedBy', default=1, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='incidents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Incidents',
                'verbose_name_plural': 'Incidents',
                'db_table': 'incident',
                'ordering': ['-incidentdate'],
            },
        ),
    ]
