# Generated by Django 4.0.3 on 2023-04-24 04:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('incident', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incident',
            name='incidentid',
            field=models.AutoField(db_column='incidentid', editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='incident',
            name='recordedby',
            field=models.ForeignKey(db_column='recordedby', default='staff', on_delete=django.db.models.deletion.SET_DEFAULT, related_name='incidents', to=settings.AUTH_USER_MODEL),
        ),
    ]
