# Generated by Django 4.0.3 on 2023-06-23 10:25

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('incident', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incident',
            name='incidentid',
            field=models.UUIDField(db_column='incidentid', default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
