# Generated by Django 4.0.3 on 2023-06-23 10:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('incident', '0002_alter_incident_incidentid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incident',
            name='incidentdate',
            field=models.DateTimeField(auto_now_add=True, db_column='incidentdate'),
        ),
        migrations.AlterField(
            model_name='incident',
            name='incidentremarks',
            field=models.TextField(blank=True, db_column='incidentremarks'),
        ),
        migrations.AlterField(
            model_name='incident',
            name='locationremarks',
            field=models.TextField(blank=True, db_column='locationremarks'),
        ),
        migrations.AlterField(
            model_name='incident',
            name='recordedby',
            field=models.ForeignKey(db_column='recordedby', default=1, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='incidents', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='incident',
            name='speciesname',
            field=models.CharField(blank=True, db_column='speciesname', max_length=100),
        ),
        migrations.AlterField(
            model_name='incident',
            name='speciestype',
            field=models.CharField(choices=[('Mammal', 'Mammal'), ('Bird', 'Bird'), ('Other', 'Other')], db_column='speciestype', default='Bird', max_length=50),
        ),
    ]
